name: py-rest-101

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8.1
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Docker Build
      run: docker build -f Dockerfile-CI -t ${{secrets.DOCKERHUB_USER}}/$REPO:$GITHUB_SHA -t docker.pkg.github.com/yousee/$REPO/$REPO:$GITHUB_SHA  .
    - name: Docker Push DockerHub
      run: |
        docker login --username ${{secrets.DOCKERHUB_USER}} --password ${{secrets.DOCKERHUB_PASSWORD}}
        docker push ${{secrets.DOCKERHUB_USER}}/$REPO
        
